name: my_app
description: "A minimal Flutter app for library management"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc_lint: ^0.3.6
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  device_preview: ^1.3.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_secure_storage: ^10.0.0
  get_it: ^9.2.0
  go_router: ^17.0.1
  hydrated_bloc: ^10.1.1
  logger: ^2.6.2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.4
  sizer: ^3.1.3
  slang: ^4.11.1
  slang_flutter: ^4.11.0
  very_good_analysis: ^10.0.0

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env.dev
    - .env.prod
